blog/urls.py
from django.urls import path
from .views import (
	blog_home_view,
	create_post_view,
	update_post_view,
	delete_post_view,
	post_view,
	posts_view,
	my_posts_view,
	search_posts_view,
	add_comment_view,
	edit_comment_view,
	delete_comment_view,
)

urlpatterns = [
	path('blog_home/', blog_home_view, name="blog_home"),
	path('blog/create_post/', create_post_view, name="create_post"),
	path('blog/<int:post_id>/update/', update_post_view, name="update_post"),
	path('blog/<int:post_id>/delete/', delete_post_view, name="delete_post"),
	path('blog/<int:post_id>/', post_view, name="post"),

	path('blog/posts/', posts_view, name="all_posts"),

	path('blog/my-posts/', my_posts_view, name="my_posts"),

	path('blog/posts/search/', search_posts_view, name="search_posts"),
	path('blog/<int:post_id>/comment/', add_comment_view, name="add_comment"),
	path('post/<int:post_id>/<comment_id>/edit/', edit_comment_view, name="edit_comment"),
	path('post/<int:post_id>/<comment_id>/delete/', delete_comment_view, name="delete_comment")
]

learner/urls.py
from django.urls import path
from .views import (
    learner_registration_view,
    learner_account_update,
)

urlpatterns = [
    path('learner/register/', learner_registration_view, name="learner_account_reg"),
    path('learner/account/update/', learner_account_update, name="learner_account_update")
	
]

schoolweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from account import urls as BaseAccountUrls
from friend import urls as FriendUrls
from unique import urls as UniqueUrls
from learner import urls as LearnerUrls
from teacher import urls as TeacherUrls
from blog import urls as BlogUrls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(BaseAccountUrls)),
    path('', include(UniqueUrls)),
    path('', include(FriendUrls)),
    path('', include(LearnerUrls)),
    path('', include(TeacherUrls)),
    path('', include(BlogUrls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learner/models.py
from django.db import models
from django.conf import settings
from .utils import sports, clubs, streams, grades

class LearnerAccount(models.Model):
	user 			= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	# Extra fields
	stream 			= models.CharField(choices=streams, verbose_name="stream", max_length=100, null=True, blank=True)
	grade 			= models.IntegerField(choices=grades, verbose_name="grade", null=False, blank=False)
	sport 			= models.CharField(choices=sports, verbose_name="sport", max_length=100, null=True, blank=True)
	club 			= models.CharField(choices=clubs, verbose_name="club", max_length=100, null=True, blank=True)

	is_active 	= models.BooleanField(default=True)	

	def __str__(self):
		return self.user.username
	

learner/forms.py
from django import forms
from .models import LearnerAccount

class LearnerAccountRegistration(forms.ModelForm):

    class Meta:
        model = LearnerAccount
        fields = ('grade', 'stream', 'sport', 'club')

    grade           = forms.IntegerField(required=True, min_value=7, max_value=12)
    stream          = forms.CharField(required=True, max_length=100)
    sport           = forms.CharField(required=True, max_length=100)
    club            = forms.CharField(required=True, max_length=100)


    def clean(self):
        grade = self.cleaned_data['grade']
        stream = self.cleaned_data['stream']
        if stream != 'None' and grade < 10:
            raise  forms.ValidationError("You cannot pick a stream because of your grade")
        elif grade >= 10 and stream == 'None':
            raise forms.ValidationError(f"You must pick a valid stream if you are in grade {grade}")



class LearnerAccountEdit(forms.ModelForm):

    class Meta:
        model = LearnerAccount
        fields = ('grade', 'stream', 'sport', 'club')

    def clean(self):
        grade = self.cleaned_data['grade']
        stream = self.cleaned_data['stream']
        if stream != 'None' and grade < 10:
            raise  forms.ValidationError("You cannot pick a stream because of your grade")
        elif grade >= 10 and stream == 'None':
            raise forms.ValidationError(f"You must pick a valid stream if you are in grade {grade}")
 

learner/views.py
from django.shortcuts import render, redirect
from .models import LearnerAccount
from account.models import BaseAccount
from .forms import LearnerAccountRegistration, LearnerAccountEdit
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

# @login_required(login_url="login")
# def learner_registration_view(request, *args, **kwargs):
#     context = {}
#     auth_user = request.user

#     if not auth_user.is_authenticated:
#         return redirect('login')

#     elif auth_user.is_authenticated:
#         subject_user_id = kwargs.get("subject_user_id")
#         if subject_user_id:
#             account = BaseAccount.objects.get(id=subject_user_id)

#             if account and account.is_learner:
#                 context['form'] = LearnerAccountEdit()

#                 if request.method == "POST" and request.POST:
#                     form = LearnerAccountRegistration(request.POST)
#                     if form.is_valid():
#                         try:
#                             learner = LearnerAccount.objects.get(user=auth_user)
#                         except LearnerAccount.DoesNotExist:
#                             learner_account = form.save(commit=False)
#                             learner_account.user = auth_user
#                             learner_account.save()
#                             return redirect('home')
#                         return HttpResponse("You already have a learner account")

#                     else:
#                         form = LearnerAccountRegistration(request.POST)
#                         context['form'] = form
#             else:
#                 return render(request, "errors/not_allowed.html")

#     return render(request, "learner/reg.html", context)

# @login_required(login_url="login")
# def learner_account_update(request, *args, **kwargs):
#     context = {}
#     auth_user = request.user

#     if not auth_user.is_authenticated:
#         return redirect('login')
#     elif auth_user.is_authenticated:
#         subject_user_id = 
#         auth_user = BaseAccount.objects.get(id=subject_user_id)
#         if auth_user and auth_user.is_learner:
#             try:
#                 learner_account = LearnerAccount.objects.get(user=auth_user)
#                 context['learner_account'] = learner_account
#             except:
#                 return render(request, template_name="errors/does_not_exist.html")
#             if request.method == "POST" and request.POST:
#                     form = LearnerAccountEdit(request.POST)
#                     if form.is_valid():
#                         try:
#                             grade = form.cleaned_data['grade']
#                             stream = form.cleaned_data['stream']
#                             club = form.cleaned_data['club']
#                             sport = form.cleaned_data['sport']

#                             learner_account.grade = grade
#                             learner_account.stream = stream
#                             learner_account.club = club
#                             learner_account.sport = sport
#                             learner_account.save()
#                             return redirect('account', subject_user_id=auth_subject_user_id)
                            
#                         except:
#                             form = LearnerAccountRegistration(request.POST)
#                             context['form'] = form

#                         return HttpResponse("You already have a learner account")
#                     else:
#                         form = LearnerAccountEdit(request.POST)
#                         context['form'] = form
#         else:
#             return render(request, "errors/not_allowed.html")
#     return render(request, "learner/edit.html", context)
    
@login_required(login_url="login")
def learner_registration_view(request, *args, **kwargs):
    context = {}
    auth_user = request.user
    if not auth_user.is_authenticated:
        return redirect("login")

    if auth_user.is_authenticated:

        if auth_user.is_learner:
            
            if request.method == "POST" and request.POST:
                form = LearnerAccountRegistration(request.POST)

                if form.is_valid():
                    try:
                        learner_account = LearnerAccount.objects.get(user=auth_user)
                        return render(request, template_name="errors/done.html")
                    except LearnerAccount.DoesNotExist:
                        learner_account = form.save(commit=False)
                        learner_account.user = auth_user
                        learner_account.save()
                        return redirect('account', subject_user_id=auth_user.id)
                    
                    else:
                        form  = LearnerAccountRegistration(request.POST)
                        context['form'] = form
            else:
                return render(request, "errors/not_allowed.html")

    return render(request, "learner/reg.html", context)

@login_required(login_url="login")
def learner_account_update(request, *args, **kwargs):
    context = {}
    auth_user = request.user

    if not auth_user.is_authenticated:
        return redirect('login')

    elif auth_user.is_authenticated:
        subject_user_id = kwargs.get("subject_user_id")
        auth_user = BaseAccount.objects.get(id=auth_user.id)
        if auth_user and auth_user.is_learner:
            try:
                learner_account = LearnerAccount.objects.get(user=auth_user)
                context['learner_account'] = learner_account
            except:
                return redirect("reg_complete")

            if request.method == "POST" and request.POST:
                form = LearnerAccountEdit(request.POST)
                if form.is_valid():
                    try:
                        grade = form.cleaned_data['grade']
                        stream = form.cleaned_data['stream']
                        club = form.cleaned_data['club']
                        sport = form.cleaned_data['sport']

                        learner_account.grade = grade
                        learner_account.stream = stream
                        learner_account.club = club
                        learner_account.sport = sport
                        learner_account.save()
                        return redirect('account', subject_user_id=auth_user.id)
                    except Exception as e:
                        form = LearnerAccountEdit(request.POST)
                        context['form'] = form
                else:
                    form = LearnerAccountEdit(request.POST)
                    context['form'] = form
            else:
                pass
        else:
            return render(request, "errors/not_allowed.html")

    return render(request, "learner/edit.html", context)
    
     

templates/learner/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-md-7">
			<div class="card my-4 border border-dark ">
				<div class="card-body">
					<h2 class="card-title card-h">Update Learner account</h2>
					<form method="POST">{% csrf_token %}
							<div class="form-group">
								<label for="id_grade">Grade</label>
								<select name="grade" required="" id="id_grade" class="form-control">
									<option selected value={{learner_account.grade}}>{{learner_account.grade}}</option>
									<option value=8>8</option>
									<option value=9>9</option>
									<option value=10>10</option>
									<option value=11>11</option>
									<option value=12>12</option>
								</select>
							</div>

								<label for="id_stream">Stream</label>
								<select name="stream" required="" id="id_stream" class="form-control">
									<option selected value="{{learner_account.stream}}">{{learner_account.stream}}</option>
									<option value="Technical stream 1">Technical stream 1</option>
									<option value="Technical stream 2">Technical stream 2</option>
									<option value="Science">Science</option>
									<option value="Information technology">Information technolofy (I.T)</option>
									<option value="None">None</option>
									<option value="Commerce">Commerce</option>
								</select>
							</div>



							<div class="form-group">
								<label for="id_sport" class="label">Sport</label>
								<select name="sport" id="id_sport" class="form-control">
								<option selected value={{ learner_account.sport}}>{{learner_account.sport}}</option>
									<option calue="None">None</option>
									<option value="Chess">Chess</option>
									<option value="Tennis">Tennis</option>
									<option value="Soccer">Soccer</option>
									<option value="Netball">Netball</option>

								</select>
							</div>

							<div class="form-group">
								<label for="id_club" class="label">Club</label>
								<select name="club" id="id_club" class="form-control">
								<option selected value={{ learner_account.club}}>{{learner_account.club}}</option>
									<option calue="None">None</option>
									<option value="Robotics">Robotics</option>
									<option value="Science">Science</option>
									<option value="English society">English society</option>
								</select>
							</div>

						{% for field in form %}
							<p>
							{% for error in field.errors %}
								<p style="color: red">{{ error }}</p>
							{% endfor %}
							</p>
						{% endfor %}
						{% if form.non_field_errors %}
							<div style="color: red">
								<p>{{ form.non_field_errors }}</p>
							</div>
						{% endif %}
						<br>
						<button class="btn btn-primary m-2">Save</button>
					</form> 
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/learner/reg.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Learner registration
{% endblock title %}


{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-7">
        <div class="card my-4">
          <div class="card-body">
              <form class="form" method="POST">{% csrf_token %}

                    <div class="form-group">
                        <label for="id_grade">Grade</label>
                        <select name="grade" required="" id="id_grade" class="form-control">
                            <option value=8>8</option>
                            <option value=9>9</option>
                            <option value=10>10</option>
                            <option value=11>11</option>
                            <option value=12>12</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="id_stream">Stream choices</label>
                        <select name="stream" id="id_stream" class="form-control" required>
                            <option value="None">None</option>
                            <option value="Technichal stream 2">Technichal stream 2</option>
                            <option value="Technichal stream 1">Technichal stream 1</option>
                            <option value="Commerce">Commerce</option>
                            <option value="Science">Science</option>
                        </select>
                    </div>

                        <div class="form-group">
                            <label for="id_sport" class="label">Sport</label>
                            <select name="sport" id="id_sport" class="form-control">
                                <option calue="None">None</option>
                                <option value="Chess">Chess</option>
                                <option value="Tennis">Tennis</option>
                                <option value="Soccer">Soccer</option>
                                <option value="Netball">Netball</option>

                            </select>
                        </div>

                        <div class="form-group">
                            <label for="id_club" class="label">Club</label>
                            <select name="club" id="id_club" class="form-control">
                                <option calue="None">None</option>
                                <option value="Robotics">Robotics</option>
                                <option value="Science">Science</option>
                                <option value="English society">English society</option>
                            </select>
                        </div>
                        <!-- START Error handling -->
                        {% for field in form %}
                            <p>
                            {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                            </p>
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <div style="color: red">
                                <p>{{form.non_field_errors}}</p>
                            </div>
                        {% endif %}
                        <!-- END Error handling -->
                    <button class="btn btn-primary btn-block" type="submit">Submit</button>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock%}