blog/urls.py
from django.urls import path
from .views import (
	blog_home_view,
	create_post_view,
	update_post_view,
	delete_post_view,
	post_view,
	posts_view,
	my_posts_view,
	search_posts_view,
	add_comment_view,
	edit_comment_view,
	delete_comment_view,
)

urlpatterns = [
	path('blog_home/', blog_home_view, name="blog_home"),
	path('blog/create_post/', create_post_view, name="create_post"),
	path('blog/<int:post_id>/update/', update_post_view, name="update_post"),
	path('blog/<int:post_id>/delete/', delete_post_view, name="delete_post"),
	path('blog/<int:post_id>/', post_view, name="post"),

	path('blog/posts/', posts_view, name="all_posts"),

	path('blog/my-posts/', my_posts_view, name="my_posts"),

	path('blog/posts/search/', search_posts_view, name="search_posts"),
	path('blog/<int:post_id>/comment/', add_comment_view, name="add_comment"),
	path('post/<int:post_id>/<comment_id>/edit/', edit_comment_view, name="edit_comment"),
	path('post/<int:post_id>/<comment_id>/delete/', delete_comment_view, name="delete_comment")
]

schoolweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from account import urls as BaseAccountUrls
from friend import urls as FriendUrls
from unique import urls as UniqueUrls
from learner import urls as LearnerUrls
from teacher import urls as TeacherUrls
from blog import urls as BlogUrls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(BaseAccountUrls)),
    path('', include(UniqueUrls)),
    path('', include(FriendUrls)),
    path('', include(LearnerUrls)),
    path('', include(TeacherUrls)),
    path('', include(BlogUrls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from .utils import post_types
# Create your models here.

class Comment(models.Model):

	author  		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	content 		= models.CharField(verbose_name="comment", max_length=250, null=False, blank=False)
	post 			= models.ForeignKey('Post', verbose_name="post", on_delete=models.CASCADE, blank=False, null=False)
	timestamp 		= models.DateTimeField(verbose_name="timestamp", auto_now_add=True)
	is_active 		= models.BooleanField(default=True, verbose_name="is_active")

	def __str__(self):
		return self.author.username

class Post(models.Model):

	author 		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="author")
	title 		= models.CharField(verbose_name="title", max_length=200, null=False, blank=False, unique=False)
	intro		= models.CharField(verbose_name="intro", max_length=500, blank=True, unique=False)
	content 	= models.CharField(verbose_name="content", max_length=5000, null=True, blank=True, unique=False)
	post_type 	= models.CharField(choices=post_types, verbose_name="post_type", null=False, blank=False, max_length=100, default='General')

	views 		= models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="views", blank=True)
	comments 	= models.ManyToManyField(Comment, related_name="comments", blank=True)
	timestamp 	= models.DateTimeField(verbose_name="timestamp", auto_now_add=True)

	is_active 		= models.BooleanField(default=True, verbose_name="is_active")
	draft 		= models.BooleanField(verbose_name="draft", default=True)

	# Groups it will be visible to
	grade 		= models.BooleanField(verbose_name="grade", default=False)
	stream 		= models.BooleanField(verbose_name="stream", default=False)
	sport 		= models.BooleanField(verbose_name="sport", default=False)
	club 		= models.BooleanField(verbose_name="club", default=False)
	teachers 	= models.BooleanField(verbose_name="teachers", default=False)

	def __str__(self):
		return self.author.username + ' | ' + self.title
	
	def public(self):
		self.draft = False
		self.save()

	def is_draft(self):
		return self.is_draft

	def viewcount(self):
		viewcount = len(self.views)
		return viewcount

	def viewers(self):
		viewers = self.views.all()
		return viewers

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post, Comment
from account.models import BaseAccount
from .form import CreatePostForm, UpdatePostForm, EditCommentForm
import json
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
# Create your views here.

# Optimized

def blog_home_view(request, *args, **kwargs):
	auth_user = request.user
	
	if not auth_user.is_authenticated:
		return redirect('login')

	if auth_user.is_authenticated:
		return render(request, "blog/blog.html")


# Optimized

def create_post_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return render(request,template_name="errors/not_auth.html")

	if auth_user.is_authenticated:
		try:
			auth_account = BaseAccount.objects.get(id=auth_user.id)
		except:
			return render(request, template_name="errors/does_not_exist.html")

		context['account'] = auth_account

		# If the form is being submitted
		if request.method == "POST":
			try:
				if request.POST:
					form = CreatePostForm(request.POST)
					if form.is_valid:
						print("[+] Form is valid and is saved")
						try:
							post = form.save(author=auth_account)
							return redirect('post' , post_id=post.id)
						except:
							print("[-] Form won't save")
					else:
						form = CreatePostForm(request.POST)
						context['form'] = form
			
			except Exception as e:
				return render(request, template_name="errors/try_again.html")
				print(str(e))

	return render(request, template_name="blog/post/create.html")

# post id
# Optimized

def update_post_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return redirect('login')

	if auth_user.is_authenticated:
		post_id = kwargs.get("post_id")
		
		try:
			auth_account = BaseAccount.objects.get(id=auth_user.id)
			post = Post.objects.get(id=post_id)
			context['post'] = post

		except BaseAccount.DoesNotExist or Post.DoesNotExist:
			return render(request, "errors.does_not_exist.html")

		if auth_account and request.method == "POST":
			form = UpdatePostForm(request.POST, instance=post)
			if form.is_valid:
				try:
					form.save()
					print("[+] Form is saved")
					return redirect('post', post_id=post_id)
				except Exception as e:
					form = UpdatePostForm(request.POST, instance=post)
					context['form'] = form	
					print("[-] Errors : "+str(e))
			else:
				form = UpdatePostForm(request.POST, instance=post)
				context['form'] = form	

	return render(request, "blog/post/update.html", context)


# Optimized
@login_required(login_url="login")
def delete_post_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return redirect('login')

	elif auth_user.is_authenticated:
		auth_user_account = BaseAccount.objects.get(id=auth_user.id)
		try:
			post_id = kwargs.get('post_id')
			if post_id:
				post = Post.objects.get(id=post_id)
				if auth_user_account and post:
					if post.author == auth_user_account:
						post.is_active = False
						post.save()
						return redirect('my_posts')
					else:
						return render(request, template_name="errors/not_allowed.html")
				else:
					return render(request, template_name="errors/does_not_exist.html")
		except:
			return render(request, "errors/try_again.html")

	return render(request, "blog/post/delete.html", context)

# Optimized
@login_required(login_url="login")
def post_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return render(request, template_name="errors/not_auth.html")

	if auth_user.is_authenticated:
		post_id = kwargs.get("post_id")
		
		if post_id:
			post = Post.objects.get(id=post_id)
			if post:
				context['post'] = post
				comments = []
				# get the authenticated users friend list
				comment_model = Comment.objects.filter(post=post, is_active=True).order_by('-timestamp')
				if comment_model:
					for comment in comment_model:
						is_mine = None
						if comment.author == auth_user:
							my_comment = True
						else:
							my_comment = False

						if comment.post == post and comment.is_active == True:
							comments.append((comment, my_comment))

				context['comments'] = comments
				# Viewcount feature
				if post.author != auth_user:
					post.views.add(auth_user)
					post.save()

				viewers = post.views.all()
				context['views'] = viewers

				if auth_user == post.author:
					is_mine = True
					context['is_mine'] = is_mine
				else:
					is_mine = False
					context['is_mine'] = is_mine
			else:
				return render(request, template_name="errors/does_not_exist.html")
		else:
			return render(request, template_name="errors/not_allowed.html")

	return render(request, "blog/post/post.html", context)

# Optimized
@login_required(login_url="login")
def posts_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return redirect('login')

	elif auth_user.is_authenticated:
		auth_user_account = BaseAccount.objects.get(id=auth_user.id)
		try:
			posts = []
			posts_list = Post.objects.filter(is_active=True).order_by('-timestamp')
			if posts_list:
				for post in posts_list:
					is_mine = False
					if auth_user_account == post.author:
						is_mine = True
					if not post.draft:
						posts.append((post, is_mine))
				# Pagination
				p = Paginator(posts, 5)
				page = request.GET.get('page')
				posts_list_paginated = p.get_page(page)
				context['posts'] = posts_list_paginated
			else:
				return render(request, template_name="errors/try_again.html")	
		except:
			return render(request, template_name="errors/does_not_exist.html")

	return render(request, "blog/post/posts.html", context)

# Optimized
@login_required(login_url="login")
def my_posts_view(request, *args, **kwargs):

	print('[+] My posts view runnign')
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return redirect('login')

	elif auth_user.is_authenticated:

		auth_user_account = BaseAccount.objects.get(id=auth_user.id)

		try:
			posts_list = Post.objects.filter(is_active=True, author=auth_user_account).order_by('-timestamp')
			# Pagination
			p = Paginator(posts_list, 5)
			page = request.GET.get('page')
			posts_list_paginated = p.get_page(page)
			context['posts'] = posts_list_paginated
		except:
			return render(request, template_name="errors/does_not_exist.html")

	return render(request, "blog/post/my_posts.html", context)

# Optimized
@login_required(login_url="login")
def search_posts_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return redirect('login')

	elif auth_user.is_authenticated:

		if request.method == "GET":
			search_query = request.GET.get("q")
			if len(search_query) > 0:
				search_results = Post.objects.filter(title__icontains=search_query).distinct().order_by('-timestamp')

				# [(post1, True), (post2, False), ...]
				posts = []
				for post in search_results:
					if user == post.author:
						is_mine = True
					else:
						is_mine = False
					posts.append((post, is_mine))
				context['posts'] = posts
				
	return render(request, "blog/search.html", context)

# Optimized
@login_required(login_url="login")
def add_comment_view(request, *args, **kwargs):
	context = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return redirect('login')

	elif auth_user.is_authenticated:
		auth_user_account = BaseAccount.objects.get(id=auth_user.id)

		if request.method == "POST":
			post_id = kwargs.get("post_id")

			payload = {
				"response" : ""
			}
			
			if post_id:
				comment = request.POST.get("data")
				author = auth_user_account
				post = Post.objects.get(id=post_id)
				if comment and post:
					comment = Comment.objects.create(author=author, content=comment, post=post)
					comment.save()
					payload['response'] = "[+] Comment added"
				else:
					payload['response'] = "[-] Models do not exists"
					return render(request, "errors/does_not_exist.html")
			else:
				payload['response'] = "Keyword args are not valid"
				return render(request, "errors/does_not_exist.html")

		if payload['response'] == None:
			payload['response'] = "Default because it was none"
	else:
		return redirect('login')

	return HttpResponse(json.dumps(payload), content_type="application/json")

# Optimized
@login_required(login_url="login")
def edit_comment_view(request, *args, **kwargs):
	payload = {}
	auth_user = request.user

	if not auth_user.is_authenticated:
		return render(request, template_name="errors/not_auth.html")

	elif auth_user.is_authenticated:
		try:
			comment_id = kwargs.get("comment_id")
			post_id = kwargs.get('post_id')

			if post_id and comment_id:
				try:
					post = Post.objects.get(id=post_id)
					comment = Comment.objects.get(id=comment_id)
					if post and comment:
						if not comment.author == auth_user:
							return render(request, template_name="erros/not_allowed.html")

						if request.method == "POST":
							form = EditCommentForm(request.POST)
							if form.is_valid():
								content = request.POST.get("content")
								comment.content = content
								comment.save()
								return redirect('post', post_id=post_id)
								print("[+] Edit comment form is saved")
							else:
								form = EditCommentForm(request.POST)
								context['form'] = form
					else:
						return render(request, template_name="errors/does_not_allowed.html")
				
				except Exception as e:
					print("[+] Error : "+str(e))
		
		except Exception as e:
			print("[+] Error : "+str(e))

	return redirect('post', post_id=post_id, user_id=user.id)

# Optimized
@login_required(login_url="login")
def delete_comment_view(request, *args, **kwargs):
	auth_user = request.user
	context = {}

	if not auth_user.is_authenticated:

templates/blog/post/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Register
{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card my-4 border border-dark ">
				<div class="card-body">
					<h2 class="card-title card-h">Create post</h2>
                    <form class="form" method="POST">{% csrf_token %}
                        <!-- All required | Name fields are used in the backend -->
                        <input type="text" name="title" id="input_post_title" class="form-control m-2" placeholder="Post title" required autofocus>

                        <div class="form-group">
						  <small>Introduction (optional)</small>
						  <textarea class="form-control" name="intro" id="input_intro" rows="3"></textarea>
						</div>

                        <div class="form-group">
						  <small>Content</small>
						  <textarea class="form-control" name="content" id="input_content" rows="3" required></textarea>
						</div>

						<label for="id_draft" class="form-check-label m-1">Draft:</label>
						<input class="m-1" type="checkbox" name="draft" id="input_draft" checked>
						<hr>
                    	<ul class="list-unstyled mb-0">
                            <li>Teachers:<input class="m-1" type="checkbox" name="teachers" id="input_teachers" {% if post.teachers %}checked{% endif %}></li>
                            <li>Grade:<input class="m-1" type="checkbox" name="grade" id="input_grade" {% if post.grade %}checked{% endif %}></li>
                            <li>Sport:<input class="m-1" type="checkbox" name="sport" id="input_sport" {% if post.sport %}checked{% endif %}></li>
                            <li>Stream:<input class="m-1" type="checkbox" name="stream" id="input_stream" {% if post.stream %}checked{% endif %}></li>
                            <li>Club:<input class="m-1" type="checkbox" name="club" id="input_club" {% if post.club %}checked{% endif %}></li>
                        </ul>
                        <!-- START Error handling -->
                        {% for field in form %}
                            <p>
                            {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                            </p>
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <div style="color: red">
                                <p>{{form.non_field_errors}}</p>
                            </div>
                        {% endif %}
                        <!-- END Error handling -->

                        <button type="submit" class="btn btn-primary m-2 btn-block">Post</button>
                    </form>
                </div>
                <div class="card-footer text-muted">
					<button class="btn btn-primary" type="button"><a href="{% url 'home' %}" class="text-light">HOME</a></button>
                </div>            
            </div>
        </div>
    </div>
</div>

<!-- END Form -->
{% endblock content %}

templates/blog/post/my_posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-md-7">
			<div class="border-top border-bottom border-dark m-3 p-2 form-inline">
				<h1 class="pt-2 card-h">POSTS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
				<button class="btn btn-default border border-success shadow" style="right: 10px;"><a href="{% url 'create_post' %}" class="text-success">Create</a></button>
					
				<div class="btn-group dropright">
					<button class="btn btn-secondary dropdown-toggle" type="button" aria-haspopup="true" aria-expanded="false">Filters</button>
					<div class="dropdown-menu">
					<a class="text-dark" href="#">Grade</a>
					</div>
				</div>
			</div>
			{% if posts %}
				{% for post in posts%}
					<div class="card m-3 shadow border">
						<div class="card-body">
							<h2 class="card-h card-title"><a href="{% url 'post' post_id=post.id %}" class="text-dark">{{ post.title }}</a></h2>
							<p class="card-text">{{ post.intro|truncatechars:50}}</p>
							<a href="{% url 'post' post_id=post.id %}" class="#">Read More &rarr;</a>
						</div>
						<div class="card-footer text-muted">
							<p>Posted on {{ post.timestamp }}
								<button class="btn btn-default border border-primary shadow" type="button">
									<a href="{% url 'update_post' post_id=post.id %}" class="text-primary">Update</a>
								</button>
								<button class="btn btn-default border border-danger shadow" type="button">
									<a href="{% url 'delete_post' post_id=post.id %}" class="text-danger">Delete</a>
								</button></p>
						</div>	
					</div>
				{% endfor %}
			{% else %}
				<div class="card-body">
					<center><p class="card-text">No posts :(</p></center>
        		</div>
			{% endif  %}
		</div>
		<div class="col-md-4">

			<ul class="pagination justify-content-center mb-4">
				<li class="page-item">
					{% if posts.has_previous %}
					<a class="page-link" href="?page={{ posts.previous_page_number }}">&larr; Newer</a>
					{% endif %}
				</li>
				<li clas="page-item">
					<a class="page-link" href="#">{{ posts.number }} of {{ posts.paginator.num_pages }}</a>
				</li>
				<li class="page-item">
					{% if posts.has_next %}
					<a class="page-link" href="?page={{ posts.next_page_number }}">Older &rarr;</a>
					{% endif %}
				</li>
			</ul>

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for posts...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
    <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
            <div class="row">
				<div class="col-lg-12">
          <button class="btn btn-default border border-dark btn-block m-1">
          <a href="#" class="text-dark">General</a>
          </button>
				</div>
            	<div class="col-lg-6">


                <ul class="list-unstyled mb-0">
                  <li>
                   <button class="btn btn-default border border-dark btn-block m-1">
				   	<a href="#" class="text-dark">Grade 10</a>
				   </button>
                  </li>
                  <li>
                   <button class="btn btn-default border border-dark btn-block m-1">
				   	<a href="#" class="text-dark">Stream</a>
				   </button>
                  </li>
                  <li>
                   <button class="btn btn-default border border-dark btn-block m-1">
				   	<a href="#" class="text-dark">Sport</a>
				   </button>
                  </li>
                  </li>
                   <button class="btn btn-default border border-dark btn-block m-1">
				   	<a href="#" class="text-dark">Club</a>
				   </button>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                   <button class="btn btn-default border border-success btn-block m-1">
				   	<a href="#" class="text-success">Announcements</a>
				   </button>
                  </li>
                   <button class="btn btn-default border border-danger btn-block m-1">
				   	<a href="#" class="text-danger">Notice</a>
				   </button>
                  </li>
				</li>
                   <button class="btn btn-default border border-primary btn-block m-1">
				   	<a href="#" class="text-primary">Updates</a>
				   </button>
                  </li>
                  </li>
                   <button class="btn btn-default border border-success btn-block m-1">
				   	<a href="#" class="text-success">Important</a>
				   </button>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
		</div>
	</div>
</div>

{% endblock content %}

templates/blog/post/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Blog
{% endblock %}


{% block content %}

<style type="text/css">
    .pp-image {
        width: 20px;
        height: 20px;
        }
</style>


  <!-- Page Content -->
<div class="container-fluid">
	<div class="row justify-content-center">
        <div class="col-md-10">
            <h1 class="card-h mt-4">{{ post.title }}</h1>
            <p class="lead">
                by
                <a href="{% url 'account' subject_user_id=post.author.id %}">{% if request.user == post.author %}You{% else %}{{ post.author }}{% endif %}</a>
            </p>
            <div class="border border-info mb-2"></div>
            <p>Posted on {{ post.timestamp.date }}</p>
            <div class="border border-info"></div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6 mt-2">
            <div class="card border border-secondary shadow">
                <p class="lead card-title">{{ post.intro|escape|linebreaksbr }}</p>
                <div class="card-body shadow">
                    <p>{{ post.content|escape|linebreaksbr }}</p>
                </div>
                <div class="card-footer text-muted pb-0">
                    {% if is_mine %}
                        <p><button class="btn btn-default border border-primary shadow" type="button">
                            <a href="{% url 'update_post' post_id=post.id %}" class="text-primary">Update</a>
                        </button>
                        <button class="btn btn-default border border-danger shadow" type="button">
                            <a href="{% url 'delete_post' post_id=post.id %}" class="text-danger">Delete</a>
                        </button>
                            <span class="pl-3">views : {{ views|length }}</span>
                        </p>
                    {% else %}
                    <p><button class="btn btn-default border border-dark text-dark align-right">views : {{ views|length }}</button></p>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card border border-secondary mt-2 shadow">
                <div class="card-header">
                    <h3 class="card-h">Comments</h3>
                </div>
                <div class="card-body">
                <div class="input-group">
                    <input type="text" class="form-control border border-info shadow" id="id_comment_input" placeholder="Add a comment...">
                    <span class="input-group-append">
                        <button class="btn btn-info border rounded-right shadow" type="button" onclick="triggerAddComment()">Go!</button>
                    </span>
                </div>
                {% if comments %}

                    {% for comment in comments %}
                    <div class="card my-4 shadow">
                        <a href="{% url 'account' subject_user_id=comment.0.author.id %}" class="text-dark font-weight-bold pt-2 pl-1"><img class="pp-image rounded-circle" src="{% static 'pp.png' %}" alt="profile image" /><small>{% if comment.1 %}You{% else %}{{ comment.0.author }}{% endif %}</small></a>
                        <hr>
                        <p class="card-text pl-2">{{ comment.0.content }}<br>
                            <div class="card-footer pl-1 pb-0">
                            <small>{{ comment.0.timestamp.date }}</small>
                            {% if comment.1 %}
                            <button class="btn btn-danger">
                                <a href="{% url 'delete_comment' post_id=post.id comment_id=comment.0.id %}" class="text-light">
                                Delete
                                </a>
                            </button>
                            
                            <form method="POST" action="{% url 'edit_comment' post_id=post.id comment_id=comment.0.id %}">{% csrf_token %}
                                <input type="text" class="form-control border border-info shadow" name="content" id="id__edit_comment_input" value="{{ comment.0.content}}">
                                <input type="hidden" id="id_comment_id" name="comment_id" value="{{ comment.0.id }}">
                                <span class="input-group-append">
                                    <button id="id_edit_comment_btn" class="btn btn-info border rounded-right shadow" type="submit">Go!</button>
                                </span>
                                {% for field in form %}
                                    <p>
                                    {% for error in field.errors %}
                                        <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                    </p>
                                {% endfor %}
                                {% if form.non_field_errors %}
                                    <div style="color: red">
                                        <p>{{ form.non_field_errors }}</p>
                                    </div>
                                {% endif %}
                            </form>
                            {% endif %}
                        </p>
                            </div>
                    </div>

                    {% endfor %}

                {% else %}
                <div class="card m-2 border border-primary">
                    <div class="card-body">
                        <p>No comments , yet</p>
                    </div>
                </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    function triggerAddComment() {
        var comment = "";
        var post_id = {{ post.id }};
        comment = document.getElementById('id_comment_input').value;
        addComment(post_id, comment);
    }

</script>

{% include 'blog/comment/create.html' %}
{#% include 'blog/comment/edit.html' %#}

{% endblock %}

templates/blog/post/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Update post
{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card my-4 border border-dark ">
				<div class="card-body">
					<h2 class="card-title card-h">Update post</h2>
                    <form class="form" method="POST">{% csrf_token %}
                        <!-- All required | Name fields are used in the backend -->
                        <input type="text" name="title" id="input_post_title" class="form-control m-2" placeholder="Post title" required autofocus value="{{ post.title }}">

                        <div class="form-group">
						  <small>Introduction</small>
						  <textarea class="form-control" name="intro" id="input_intro" rows="3">{{ post.intro }}</textarea>
						</div>

                        <div class="form-group">
						  <small>Content</small>
						  <textarea class="form-control" name="content" id="input_content" rows="3" required>{{ post.content }}</textarea>
						</div>

						<label for="id_draft" class="form-check-label m-1">Draft:</label>
						<input class="m-1" type="checkbox" name="draft" id="input_draft" {% if post.draft %}checked{% endif %}>
						<hr>
                
                    	<ul class="list-unstyled mb-0">
                            <li>Teachers:<input class="m-1" type="checkbox" name="teachers" id="input_teachers" {% if post.teachers %}checked{% endif %}></li>
                            <li>Grade:<input class="m-1" type="checkbox" name="grade" id="input_grade" {% if post.grade %}checked{% endif %}></li>
                            <li>Sport:<input class="m-1" type="checkbox" name="sport" id="input_sport" {% if post.sport %}checked{% endif %}></li>
                            <li>Stream:<input class="m-1" type="checkbox" name="stream" id="input_stream" {% if post.stream %}checked{% endif %}></li>
                            <li>Club:<input class="m-1" type="checkbox" name="club" id="input_club" {% if post.club %}checked{% endif %}></li>
                        </ul>
                        <!-- START Error handling -->
                        {% for field in form %}
                            <p>
                            {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                            </p>
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <div style="color: red">
                                <p>{{form.non_field_errors}}</p>
                            </div>
                        {% endif %}
                        <!-- END Error handling -->

                        <button type="submit" class="btn btn-primary m-2 btn-block">Update</button>
                    </form>
                </div>
                <div class="card-footer text-muted">
					<button class="btn btn-primary" type="button"><a href="{% url 'home' %}" class="text-light">HOME</a></button>
                </div>            
            </div>
        </div>
    </div>
</div>

<!-- END Form -->
{% endblock content %}